services:
- type: web
  name: hotel-reservation-api
  runtime: node
  repo: https://github.com/LuisPiro/ReservasHotel
  plan: free
  envVars:
  - key: URL_BASE
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start nodemon
version: "1"
