services:
  - type: web
    name: hotel-reservation-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: URL_BASE
        value: /api